<template>
  <a-modal
    :visible="visible"
    title="Modify avatar"
    :maskClosable="false"
    :confirmLoading="confirmLoading"
    :width="800"
    @cancel="cancelHandel"
  >
    <a-row>
      <a-col :xs="24" :md="12" :style="{ height: '350px' }">
        <vue-cropper
          ref="cropper"
          :img="options.img"
          :info="true"
          :autoCrop="options.autoCrop"
          :autoCropWidth="options.autoCropWidth"
          :autoCropHeight="options.autoCropHeight"
          :fixedBox="options.fixedBox"
          @realTime="realTime"
        >
        </vue-cropper>
      </a-col>
      <a-col :xs="24" :md="12" :style="{ height: '350px' }">
        <div class="avatar-upload-preview">
          <img :src="previews.url" :style="previews.img" />
        </div>
      </a-col>
    </a-row>
    <template slot="footer">
      <a-button key="back" @click="cancelHandel">cancel</a-button>
      <a-button key="submit" type="primary" :loading="confirmLoading" @click="okHandel"
        >save</a-button
      >
    </template>
  </a-modal>
</template>
<script>
import { VueCropper } from 'vue-cropper'
import store from 'store'
import axios from 'axios'
// import Vue from 'vue'

export default {
  name: 'cropperModal',
  components: {
    VueCropper,
  },
  mounted() {
    const accessToken = store.get('accessToken')
    this.authorizationHeader = {
      Authorization: `Bearer ${accessToken}`,
      AccessToken: accessToken,
    }
  },

  data() {
    return {
      visible: false,
      img: null,
      confirmLoading: false,

      options: {
        img: 'tmp', // + '/' + Vue.ls.get(USER_INFO).avatar, // The address of the cropped picture
        autoCrop: true, // Whether to generate a screenshot box by default
        autoCropWidth: 200, // The width of the screenshot frame is generated by default
        autoCropHeight: 200, // The height of the screenshot frame is generated by default
        fixedBox: true, // Fixed the size of the screenshot frame and cannot be changed
      },
      previews: {},
      url: {
        upload: 'http://localhost:3000/admin/product/upload',
      },
      authorizationHeader: {},
    }
  },
  methods: {
    edit(record) {
      const { options } = this
      this.visible = true
      this.options = Object.assign({}, options, record)
    },
    cancelHandel() {
      this.options = {
        img: './avatar2.jpg',
        autoCrop: true,
        autoCropWidth: 200,
        autoCropHeight: 200,
        fixedBox: true,
      }
      this.confirmLoading = false
      this.visible = false
    },
    okHandel() {
      const that = this
      that.confirmLoading = true
      // Get the base64 data of the screenshot
      this.$refs.cropper.getCropData((data) => {
        var file = {
          imgByte: data,
        }
        axios({
          url: that.url.upload,
          method: 'post',
          data: file,
          headers: this.authorizationHeader,
          //   {
          //     'Content-Type': 'application/json',
          //   },
        }).then((res) => {
          that.$emit('ok', res.message)
          that.cancelHandel()
        })
      })
    },
    // Event of moving box
    realTime(data) {
      this.previews = data
    },
  },
}
</script>

<style lang="scss" scoped>
.avatar-upload-preview {
  border-radius: 0 !important;
  border: 1px soild black !important;
}
.avatar-upload-preview {
  position: absolute;
  top: 50%;
  transform: translate(50%, -50%);
  width: 180px;
  height: 180px;
  border-radius: 50%;
  box-shadow: 0 0 4px #ccc;
  overflow: hidden;

  img {
    width: 100%;
    height: 100%;
  }
}
</style>
