export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_CATEGORYS = 'SET_CATEGORYS'
export const SET_LOCATIONS = 'SET_LOCATIONS'
export const SET_ORDERS = 'SET_ORDERS'
export const SET_CART = 'SET_CART'
export const SET_SELECTED_ORDER = 'SET_SELECTED_ORDER'
